default_platform(:mac)

platform :mac do

  desc "build for release"
  lane :build do
    gym(scheme: "nft-folder", output_directory: "fastlane/build", clean: true)
  end

  desc "deploy to the app store"
  lane :release do
    build
    deliver # https://docs.fastlane.tools/actions/upload_to_app_store/
  end

  desc "run the app"
  lane :dev do
    gym(
      scheme: "nft-folder",
      output_directory: "fastlane/build",
      configuration: "Debug",
      clean: false,
      skip_archive: true,
      silent: true,
      skip_package_dependencies_resolution: true,
      disable_package_automatic_updates: true,
      xcodebuild_formatter: '',
    )
    sh "open #{File.expand_path('build/nft\ folder.app')}"
  end

end